# -*- coding: utf-8 -*-
"""twt_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkQ69JtYZJTdD5Frr9Y2HFt3_w-8BsFv
"""

import streamlit as st
import numpy as np
import tensorflow as tf
import pickle
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load model and tokenizer
model = tf.keras.models.load_model("glove_lstm_attention_model.h5")
with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

# Define labels manually (3-class)
label_map = {0: "Negative", 1: "Neutral", 2: "Positive"}

# Set max sequence length
MAX_LEN = 50  # Must match your training preprocessing

# Title
st.title("Tweet Sentiment Classifier")

# User input
tweet = st.text_area("Enter a tweet for sentiment prediction:")

if st.button("Classify"):
    if tweet.strip():
        # Preprocess
        seq = tokenizer.texts_to_sequences([tweet])
        padded = pad_sequences(seq, maxlen=MAX_LEN, padding='post')

        # Predict
        pred = model.predict(padded)
        label_idx = np.argmax(pred, axis=1)[0]
        label = label_map[label_idx]

        # Display
        st.success(f"Predicted Sentiment: **{label}**")
    else:
        st.warning("Please enter a tweet.")
